services:

  gitlab:
    container_name: gitlab
    hostname: gitlab
    image: gitlab/gitlab-ce:18.2.4-ce.0
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:13000'
        pages_external_url 'http://localhost:14080'
        gitlab_pages['enable'] = true
        gitlab_pages['namespace_in_path'] = true
    volumes:
      - gitlab-config:/etc/gitlab'
      - gitlab-logs:/var/log/gitlab'
      - gitlab-data:/var/opt/gitlab'
    ports:
      - '2022:22'
      - '13000:13000'
      - '14080:14080'
    networks:
      - internal
      - external
    restart: unless-stopped

  gitlab-runner:
    hostname: gitlab-runner
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    networks:
      - internal
    volumes:
      - gitlab-runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitlab
    restart: unless-stopped

  jenkins:
    hostname: jenkins
    container_name: jenkins
    build:
      context: ./jenkins
    image: hands-on/jenkins:latest
    environment:
      - JAVA_OPTS='-Dhudson.model.DirectoryBrowserSupport.CSP="style-src ''self'' ''unsafe-inline'';"'
    volumes:
      - ./jenkins/my-config:/var/jenkins_home/my-config:ro
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - internal
      - external
    restart: unless-stopped

  jenkins-agent:
    container_name: jenkins-agent
    hostname: jenkins-agent
    build:
      context: ./cicd
      target: jenkins-agent-node
    image: hands-on/jenkins/ubuntu/cicd/jenkins-agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
      - external
    restart: unless-stopped

  ansible:
    container_name: ansible
    hostname: ansible
    build:
      context: ./cicd
      target: ansible-node
    image: hands-on/jenkins/ubuntu/cicd/ansible:latest
    volumes:
      - ./cicd/ansible/config/ansible.cfg:/etc/ansible/ansible.cfg:ro
      - ./cicd/ansible/playbook:/root/ansible/playbook:ro
    networks:
      - internal
    tty: true
    restart: unless-stopped

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-runner-config:
