- name: Deploy to Docker container
  hosts: docker_containers
  become: yes

  vars_files:
    vars_common.yml

  vars:
    jar_base: "apisl.handson.grafana.webapp.webapi"
    jar_version: "0.0.1-SNAPSHOT"
    app_name: "webapp-webapi"

  tasks:
    - name: Import the main task
      ansible.builtin.import_tasks: task_main.yml

    - name: Import a task to download pyroscope
      ansible.builtin.import_tasks: task_download_pyroscope.yml

    - name: Import a task to start webapp
      ansible.builtin.import_tasks: task_start_webapp-with-grafana.yml
