- name: Debug environment variables
  ansible.builtin.debug:
    msg: |
      user1: {{ lookup('env', 'ARTIFACTORY_USERNAME') }}
      user2: {{ artifactory_username }}
      pass1: {{ lookup('env', 'ARTIFACTORY_PASSWORD') }}
      pass2: {{ artifactory_password }}

- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Stop existing application process if running
  ansible.builtin.shell: |
    pkill -f "{{ jar_base }}" || true
  register: pkill_result
  changed_when: pkill_result.rc == 0
  failed_when: false

- name: Install OpenJDK
  ansible.builtin.apt:
    name: openjdk-21-jdk-headless
    state: present
  when: ansible_os_family == "Debian"

- name: Create application directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'

- name: Download JAR file from Artifactory
  ansible.builtin.get_url:
    url: "{{ artifactory_url }}/{{ jar_file }}"
    dest: "{{ app_dir }}/{{ jar_file }}"
    username: "{{ artifactory_username }}"
    password: "{{ artifactory_password }}"
    mode: '0644'
    validate_certs: no
